### ISSUE TITLE
OSX quicklook support

### ISSUE THREAD

**Issue by faroit** [faroit/stempeg#22]
🥳 osx seems to support stem files and has a UI to select the stem right from the quicklook window:

![image](https://user-images.githubusercontent.com/72940/63771939-6422bc80-c8d8-11e9-8051-4d70aeb89d1f.png)

However, in seems that is uses some specific metadata to read the stem track name. Currently I don't know how to do that with ffmpeg, but it would be great to find out if there is way to support this.

**Comment by faroit** [comment]
Maybe let's try https://superuser.com/questions/834244/how-do-i-name-an-audio-track-with-ffmpeg

**Comment by faroit** [comment]
Got this [working for VLC using the `handler_name` tag](https://github.com/faroit/stempeg/pull/28/files#diff-0ebebfc9117842aa900d81b23dee1822R131-R141). However still no luck for quicklook on OSX as it seems to only allow official iso languages...

Maybe bringing in @nils-werner, any idea?

**Comment by nils-werner** [comment]
Have you tried

    -metadata:s:a:1 title="Foo"

?

**Comment by faroit** [comment]
> Have you tried
> 
> ```
> -metadata:s:a:1 title="Foo"
> ```
> 

yes, actually my last comment was not correct

i use `title` for VLC and `handler_name` for ffmpegs own metadata (when using ffprobe)

```python
                        '-map',
                        "[a%d]" % idx,
                        # add title tag (e.g. displayed by VLC)
                        "-metadata:s:a:%d" % idx,
                        "title=%s" % stream_names[idx],
                        # add handler tag (e.g. read by ffmpeg < 4.1)
                        "-metadata:s:a:%d" % idx,
                        "handler=%s" % stream_names[idx],
                        # add handler tag for ffmpeg >= 4.1
                        "-metadata:s:a:%d" % idx,
                        "handler_name=%s" % stream_names[idx]
```

**Comment by nils-werner** [comment]
The `Unknown language` sounds like it may be reading the `language` metadata field. Try 

```
-metadata:s:a:1 language=eng
```

and see if it shows `English`

**Comment by faroit** [comment]
it does, but it seems to only ISO certfied languages :-(

**Comment by nils-werner** [comment]
Then you're probably out of luck...

**Comment by faroit** [comment]
Alright, macOS, you had your chance ...
