### ISSUE TITLE
i think temporaryfile needs to closed before they are removed. I am running into permission error. 

### ISSUE THREAD

**Issue by karthiek** [faroit/stempeg#3]
Hi

I am getting permission error at 
os.remove(tmps[tmp_id].name) because this temporary file is used by a different application.

Added this line
tmps[tmp_id].close()
just before
os.remove(tmps[tmp_id].name) #line 124
in read.py
to resolve the issue.

**Comment by karthiek** [comment]
Added this line
tmps[tmp_id].close() 
just before 
os.remove(tmps[tmp_id].name)  #line 124
 in read.py 
to resolve the issue.

**Comment by faroit** [comment]
Hi, yes you are right. Thanks for spotting this. 
Feel free, to create a pull request for this to fix it.

**Comment by faroit** [comment]
fixed in db56cb6. Also I made a new release. Thanks again.
