### ISSUE TITLE
Is this not working on windows? 

### ISSUE THREAD

**Issue by westside** [faroit/stempeg#4]
```
import glob, os
import stempeg
import os.path

train_path = "path_to_train/"
os.chdir(train_path)
for file in glob.glob("*.stem.mp4"):
    file_path = train_path + file
    print(os.path.isfile(file_path))
    S, rate = stempeg.read_stems(file_path)

```

Even isfile returns true, read_stems throws 'FileNotFoundError: [WinError 2] '

**Comment by faroit** [comment]
can you give more details? have you tried loading a manual absolute `file_path`?

**Comment by faroit** [comment]
can you give me the full error message, please?

**Comment by faroit** [comment]
also, did you try using the provided example file: https://github.com/faroit/stempeg/blob/master/tests/data/The%20Easton%20Ellises%20-%20Falcon%2069.stem.mp4 or running the unit tests?

**Comment by faroit** [comment]
@westside did you managed to solve it?

**Comment by westside** [comment]
Really sorry for not responding. 
I just changed the stem file to the other format.
Thank you.
If I test it, let you know by opening this issue again.

**Comment by lvbaouu** [comment]
I have this issue on mac. when i tried to   S, rate = stempeg.read_stems(file_path). it shows me that [Errno 2] No such file or directory. even when i tried the sample audio provided above and using the absolute file path

**Comment by faroit** [comment]
@lvbaouu what version of FFMPEG are you using and how did you install it?

**Comment by lvbaouu** [comment]
i used  pip install ffmpeg and it is:

pip show FFMPEG
Name: ffmpeg
Version: 1.4
Summary: ffmpeg python package url [https://github.com/jiashaokun/ffmpeg]
Home-page: https://github.com/jiashaokun/ffmpeg
Author: SkeyJIA
Author-email: 363604236@qq.com
License: MIT Licence
Location: /anaconda2/envs/deeplearning/lib/python2.7/site-packages

**Comment by lvbaouu** [comment]
When I downloaded with anaconda and try, I got the following error with the following code :

`import stempeg
S, rate = stempeg.read_stems("/Users/lzhang22/Downloads/The Easton Ellises - Falcon 69.stem.mp4")


---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-2-07cb8ffb151d> in <module>()
----> 1 S, rate = stempeg.read_stems("/Users/lzhang22/Downloads/The Easton Ellises - Falcon 69.stem.mp4")

/anaconda2/envs/deeplearning/lib/python2.7/site-packages/stempeg/read.pyc in read_stems(filename, out_type, stem_id)
     89     """
     90 
---> 91     FFinfo = FFMPEGInfo(filename)
     92 
     93     if stem_id is not None:

/anaconda2/envs/deeplearning/lib/python2.7/site-packages/stempeg/read.pyc in __init__(self, filename)
     17         super(FFMPEGInfo, self).__init__()
     18         self.filename = filename
---> 19         self.json_info = read_info(self.filename)
     20 
     21     @property

/anaconda2/envs/deeplearning/lib/python2.7/site-packages/stempeg/read.pyc in read_info(filename)
     53     ]
     54 
---> 55     out = sp.check_output(cmd)
     56     info = json.loads(out.decode('utf-8'))
     57     return info

/anaconda2/envs/deeplearning/lib/python2.7/subprocess.pyc in check_output(*popenargs, **kwargs)
    221         if cmd is None:
    222             cmd = popenargs[0]
--> 223         raise CalledProcessError(retcode, cmd, output=output)
    224     return output
    225 

CalledProcessError: Command '['ffprobe', '/Users/lzhang22/Downloads/The Easton Ellises - Falcon 69.stem.mp4', '-v', 'error', '-print_format', 'json', '-show_format', '-show_streams']' returned non-zero exit status -6`

**Comment by faroit** [comment]
check if you can run `ffprobe /Users/lzhang22/Downloads/The Easton Ellises - Falcon 69.stem.mp4 -v error -print_format json -show_format -show_streams` in the command line

**Comment by lvbaouu** [comment]
no. it gives me the following error:

`(deeplearning) LPT-010557-PU:~ lzhang22$ ffprobe /Users/lzhang22/Downloads/The Easton Ellises - Falcon 69.stem.mp4 -v error -print_format json -show_format -show_streams`


dyld: Library not loaded: @rpath/libx264.138.dylib
  Referenced from: /anaconda2/envs/deeplearning/bin/ffprobe
  Reason: image not found
Abort trap: 6

**Comment by faroit** [comment]
I would recommend starting with a fresh anaconda environment. this doesn't seem like the error is caused by stempeg.

**Comment by lvbaouu** [comment]
i tried. it still gives me the same error

**Comment by faroit** [comment]
I just checked on my machine, installing miniconda and ffmpeg4 with conda. Works fine here.
Check if you didn't install ffmpeg with homebrew.
sorry, I can't give support for anaconda or ffmpeg.

**Comment by lvbaouu** [comment]
it worked on my other computer (but have no storage space the data I want to process) but not the current one. What could have been the issues?
