### ISSUE TITLE
stem2wav 

### ISSUE THREAD

**Issue by bzvew** [faroit/stempeg#5]
Where is stem2wav? How to install that? I see stempeg 0.1.3 does not have that.

**Comment by faroit** [comment]
0.1.3 includes it (see [here](https://github.com/faroit/stempeg/blob/v0.1.3/stempeg/__init__.py). It should come when you install it via pip

**Comment by bzvew** [comment]
For stempeg 0.1.2, a message tells me where that script is installed. But 0.1.3 does not have that. I use that script from 0.1.2, works now.
